
@url= http://localhost:3016


### show all users 
GET {{url}}
content-type: application/json; 


### Delete users by ID
DELETE {{url}}/deleteuser/619baaf7cce2a44682e64dd6
content-type: application/json; 


### Add a user TEST
POST {{url}}/adduser
content-type: application/json

{
    "user": {
        "name": "Test Angie Additive",
        "username": "test",
        "email": "angie@hotmail.com"
    }
}

### Update a user
PATCH {{url}}/edituser/619baaf7cce2a44682e64dd6
content-type: application/json

{
    "email": "test@yahoo.com"
}